# Generated by Django 5.2.8 on 2025-12-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
