# Generated by Django 5.2.8 on 2025-12-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='image',
        ),
    ]
