# Generated by Django 5.2.8 on 2025-12-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_tag_post_category_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
